config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
   }

   devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update]
  
  resources :articles, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get 'tag'
    end
  end
  
  root 'articles#index'

end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, length: {maximum: 60}, presence: true 
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tag_relations, dependent: :destroy
  has_many :tag, through: :tag_relations
  accepts_nested_attributes_for :images, allow_destroy: true

  def self.search(search)
    return Article.all unless search
    Article.where('title LIKE(?)', "%#{search}%")
  end
  
  def save_tags(savearticle_tags)
    current_tags = self.tag.pluck(:name) unless self.tag.nil?
    old_tags = current_tags - savearticle_tags
    new_tags = savearticle_tags - current_tags

    old_tags.each do |old_name|
      self.tag.delete Tag.find_by(name: old_tags)
    end

    new_tags.each do |new_name|
      article_tag = Tag.find_or_create_by(name: new_name)
      self.tag << article_tag
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search, :tag]

  def index
    @articles = Article.includes(:user).order(created_at: "DESC").page(params[:page]).per(10)
  end

  def new
    @article = Article.new
    @article.images.new
  end

  def create
    @article = Article.create(article_params)
    tag_list = params[:article][:tag_ids].split(',')
    if @article.save && tag_list.count < 5
      @article.save_tags(tag_list)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def edit
    @tag_list = @article.tag.pluck(:name).join(",")
  end

  def update
    article = Article.find(params[:id])
    tag_list = params[:article][:tag_ids].split(',')
    if article.update(article_params)
      article.save_tags(tag_list)
      redirect_to article_path(article.id)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def search
    @articles = Article.search(params[:keyword]).order(id: "DESC").page(params[:page]).per(10)
  end

  def tag
    @tag = Tag.find(params[:id])
    @articles = @tag.articles.order(created_at: "DESC").page(params[:page]).per(10)
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :content, images_attributes: [:src]).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.content
  %h2.index__head
    = content_title
  .index__inner
    %ul
      - @articles.each do |article|
        %li.article
          = link_to "", article_path(article.id), class: "article__link"
          - if controller.controller_name == "articles"
            - if article.user.image?
              = image_tag article.user.image.url, class: "article__user__icon clearfix"
            - else
              = image_tag asset_path("default.png", alt: "default_icon"), class: "article__user__icon clearfix"
          .article__inner__right
            = link_to article.title, article_path(article.id), class: "article__inner__right__title"
            %br
            .article__inner__right__tag
              - if article.tag.presence
                = icon("fas", "tags", class: "fas fa-tags")
                %ul.tag__list
                  - article.tag.each do |tag|
                    %li.tag__name
                      = link_to tag.name, tag_article_path(tag.id), class: "tag__name__link"
            .article__inner__right__under
              %span by
              = link_to article.user.nickname, user_path(article.user), class: "article__user"
              %span.post__time
                %time(datatime="#{article.created_at}")
                  = time_ago_in_words(article.created_at)
              = article.liked_users.count
              %span goods
  = paginate(@articles)

app/views/articles/_footer.html.haml
%footer.footer
  .footer__inner
    = link_to "CONTACT", class: "footer__contact" 
  %p.footer__copyright © kangolog

app/views/articles/_header.html.haml
%header.header
  %h1.header__logo 
    = link_to embedded_svg("logo.svg", class: "logo"), root_path

  .header__search
    = form_with(url: search_articles_path, local: true, method: :get) do |f|
      = f.text_field :keyword, placeholder: 'search', class: "header__search__window form"
      = f.submit '検索', class: "header__search__submit"

  %ul.header__menu
    - if user_signed_in?
      %li.menu_lists
        = link_to "#{current_user.nickname}", user_path(current_user.id), class: "link"
      %li.menu_lists
        = link_to 'post', new_article_path, class: "link"
      %li.menu_lists
        = link_to 'logout', destroy_user_session_path, method: :delete, class: "link"
    - else
      %li.menu_lists
        = link_to 'ログイン', new_user_session_path, class: "link"
      %li.menu_lists
        = link_to '新規登録', new_user_registration_path, class: "link"

app/views/articles/edit.html.haml
.content
  .edit__form
    = form_with model: @article, local: true do |f|
      = f.text_field :title, placeholder: "タイトル", class: "edit__form__title form"
      %br/
      = f.text_field :tag_ids, value: @tag_list, placeholder: "タグを入力(複数つけるには、' , 'で区切ってください)", class: "edit__form__tag form"
      = f.text_area :content, placeholder: "テキストを入力", class: "edit__form__content form"
      = f.submit 'kangologに投稿', class: "edit__form__submit form"

app/views/articles/index.html.haml
.top__content
  = image_tag "logo.svg", class: "top__content__logo"
  .consept
    .concept__text
      .text__top CONCEPT
      .text__bottom
        %p kangologは「看護に関する知識を記録・共有するためのサービス」です。
        %p 記事を読むこと、記事を書くことを通して、学びを深めていきましょう。
        
= render partial: 'article', locals: { '@articles': @articles, content_title: "新着記事" }

app/views/articles/new.html.haml
.new-posts__wrapper
  .new-posts__wrapper__form
    = form_with model: @article, local: true do |f|
      = f.text_field :title, placeholder: "タイトル", class: "new-posts__wrapper__form__title form"
      = f.text_field :tag_ids, class: "new-posts__wrapper__form__tag form", placeholder: "5つまでタグを入力(複数つけるには、' , 'で区切ってください)"
      %br/
      = f.fields_for :images do |i|
        = i.file_field :src, class: "new-posts__wrapper__form__image"
        %br/
      = f.text_area :content, placeholder: "テキストを入力", class: "new-posts__wrapper__form__content form"
      %br/
      = f.submit 'kangologに投稿', class: "new-posts__wrapper__form__submit form"

app/views/articles/search.html.haml
- if @articles.present?
  = render partial: 'article', locals: { '@articles': @articles, content_title: "#{@articles.count}件の検索結果" }
- else
  .search__content
    .search__content__container
      .search__content__container__textarea
        %h2
          = "「#{params[:keyword]}」に一致する記事は見つかりませんでした。"
        %p.serch__text他のキーワードでの検索をお試しください。

app/views/articles/show.html.haml
.article__show
  .article__show__top
    .article__show__top__date
      = @article.created_at.strftime("%b %d %Y")
    - if user_signed_in? && current_user.id == @article.user_id
      .article__show__top__menu
        = link_to 'edit', edit_article_path(@article.id), class: "article__edit"
        = link_to 'delete', article_path(@article.id), method: :delete, class: "article__delete"
  .article__show__tag
    - if @article.tag
      - @article.tag.each do |tag|
        .tag__name
          = link_to tag.name, tag_article_path(tag.id)
  .article__show__title
    = @article.title
    %span by
    = link_to(@article.user.nickname, user_path(@article.user), class: "article__show__user-link")
  .article__show__content
    - if @article.images[0].present?
      .article__image
        = image_tag @article.images[0].src.to_s
    = simple_format @article.content

  .likes__block
    #likes_buttons
      = render partial: 'likes/like', locals: { article: @article }

  .article__show__comment__wrapper
    %h2.article__show__comment__wrapper__title
      = icon("far", "fa-comment-alt", class: "far fa-comment-alt")
      コメント
    - if @comments.present?
      - @comments.each do |comment|
        .article__show__comment__wrapper__table.clearfix
          .article__show__comment__wrapper__table__top
            %p.article__show__comment__wrapper__table__username
              %span @
              = link_to comment.user.nickname, user_path(comment.user_id)
            %p.article__show__comment__wrapper__table__updatedat
              = comment.updated_at.strftime("%Y-%m-%d")
          %p.article__show__comment__wrapper__table__text
            = comment.text
          - if user_signed_in? && current_user.id == comment.user.id 
            .article__show__comment__wrapper__table__menu
              = link_to 'edit', edit_article_comment_path(@article, comment)
              = link_to 'delete', article_comment_path(@article, comment), method: :delete
    - else
      %p.nocomment__content この記事にコメントはありません。
    - if current_user
      %p.article__show__comment__wrapper__formhead コメントを投稿
      .article__show__comment__wrapper__form.form.clearfix
        = form_with(model: [@article, @comment], local: true) do |f|
          = f.text_area :text, placeholder: "テキストを入力", rows: "4", class: "comment__form__textarea form"
          = f.submit "SEND", class: "comment__form__submit form"

app/views/articles/tag.html.haml
= render partial: 'article', locals: { '@articles': @articles, content_title: "#{@tag.name}の記事一覧"}