config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
   }

   devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update]
  
  resources :articles, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get 'tag'
    end
  end
  
  root 'articles#index'

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates_uniqueness_of :article_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @user = User.find(current_user.id)
    @article = Article.find(params[:article_id])
    @like = current_user.likes.create(article_id: params[:article_id])
  end

  def destroy
    @user = User.find(current_user.id)
    @article = Article.find(params[:article_id])
    @like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    @like.destroy
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
- if current_user
  - if current_user.already_liked?(article)
    = link_to article_like_path(article, current_user.likes), method: :delete, class: "likes__icon", remote: true do
      = icon("fas", "fa-heartbeat", class: "fa fa-heartbeat")
  - else
    = link_to article_likes_path(article), method: :post, class: "likes__icon", remote: true do
      = icon("far", "fa-heart", class: "fa fa-heart")
- else
  = icon("fas", "fa-heartbeat", class: "fa fa-heartbeat likes__icon")
%p.likes__count 
  = article.likes.count

app/views/likes/create.js.erb
$('#likes_buttons').html("<%= j(render partial: 'likes/like', locals: {article: @article,like: @like}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons').html("<%= j(render partial: 'likes/like', locals: {article: @article,like: @like}) %>");